# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


# Build settings

remote_theme: "mmistakes/minimal-mistakes@4.22.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme

  
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

minimal_mistakes_skin: "contrast"

locale: "en-US"
title: "Boa Constrictor"
subtitle: "The .NET Screenplay Pattern"
logo: "/assets/images/logo-symbol-black-120x148.png"
name: Q2 Holdings Inc
description: >-
  Boa Constrictor is a C# implementation of the Screenplay Pattern.
  Its primary use case is Web UI and REST API test automation.
  Boa Constrictor helps you make better interactions for better automation!

url: "https://q2ebanking.github.io"
baseurl: "/boa-constrictor"
repository: "q2ebanking/boa-constrictor"

search: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      sidebar:
        nav: "main-docs"
      header:
        og_image: /assets/images/logo-og-image.png

footer:
  links:
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/pP3dXzYQ82"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/q2ebanking/boa-constrictor/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/AutomationPanda"

github: [metadata]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
